name: Deploy docs

on: 
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.Js
        uses: actions/setup-node@v4
        with: 
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci

      - run: npm run build

      - name: Deploy storybook
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        working-directory: ./packages/docs
        path: storybook-static # default: dist/storybook
        checkout: false # default: true



        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
